version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}-php8.2-debian"
    restart: always
    working_dir: /var/www
    volumes:
      - ./src:/var/www
  nginx:
    image: nginx:stable-alpine3.17-slim
    container_name: "${PROJECT_NAME}-nginx"
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:latest
    container_name: "${PROJECT_NAME}-mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql